apiVersion: v1
kind: Service
metadata:
  name: webapplication
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
