apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlreplicaset
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqlcontainer
        image: 372159200162.dkr.ecr.us-east-1.amazonaws.com/assignment1:v0.2
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      imagePullSecrets:
        - name: regcred
